### ISSUE TITLE
Experiment with Pug in React

### ISSUE THREAD

**Issue by samhh** [OpenSourceTagpro/website#3]
See: https://github.com/pugjs/babel-plugin-transform-react-pug

**Comment by samhh** [comment]
Gave it a shot, pretty painful. Unlike Vue, React isn't really designed for use with anything other than JSX. Shame as I really miss Pug... oh well.

**Comment by sallaben** [comment]
Didn't work out? What were the main issues here?

**Comment by samhh** [comment]
It did functionally work in my limited local test, but it was just an unpleasant dev experience. With React it feels... hacky.

In React, JSX vs Pug:

JSX:

    <h1 className={styles.example}>{this.state.example}</h1>

Pug:

    pug`h1(className=${styles.example}) ${this.state.example}`

What Pug _should_ look like (e.g. in Vue):

    h1(class=styles.example)= this.state.example

Using it with React, what you gain in dropping closing tags you lose twice over in the lack of syntax highlighting in your editor and the non-standard variable interpolation.

Further, with Vue you just require `pug` and `pug-loader`. It works fairly natively via Webpack for want of a better word. With this, it is converted to JSX via Babel leaving a big maintainability concern regards the plugin.

This is the one reason why every time I use React my eye is caught wandering over to Vue... haha.
